SELECT CATEGORY, SUM(TOTAL_SALES) AS TOTAL_SALES
FROM (
    SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
    FROM BOOK AS B
    LEFT JOIN BOOK_SALES AS BS
    ON B.BOOK_ID = BS.BOOK_ID
    WHERE BS.SALES_DATE >= '2022-01-01' AND BS.SALES_DATE <= '2022-01-31'
    GROUP BY B.BOOK_ID
) TMP
GROUP BY CATEGORY
ORDER BY CATEGORY