-- 코드를 입력하세요
SELECT MEMBER_ID,MEMBER_NAME,GENDER, SUBSTRING(DATE_OF_BIRTH,1,10) AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER='W' AND TLNO IS NOT NULL AND DATE_OF_BIRTH LIKE '____-03-__'
ORDER BY MEMBER_ID